/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import org.jooq.codegen.maven.example.tables.UserInfo;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户信息表
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
