spring:
  sql:
    init:
      platform: h2
      mode: embedded #never
  jooq:
    sql-dialect: MYSQL
  datasource:
    url: "jdbc:h2:mem:test;mode=MySQL;"
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false