/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc.tables;


import com.katana.demo.entity.uc.Keys;
import com.katana.demo.entity.uc.Uc;
import com.katana.demo.entity.uc.tables.records.UserTagRecord;
import com.katana.jooq.converter.LocalDateTimeConverter;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTag extends TableImpl<UserTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>uc.user_tag</code>
     */
    public static final UserTag USER_TAG = new UserTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTagRecord> getRecordType() {
        return UserTagRecord.class;
    }

    /**
     * The column <code>uc.user_tag.id</code>.
     */
    public final TableField<UserTagRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>uc.user_tag.userid</code>.
     */
    public final TableField<UserTagRecord, Long> USERID = createField(DSL.name("userid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>uc.user_tag.tag</code>.
     */
    public final TableField<UserTagRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field("'0'", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>uc.user_tag.create_time</code>.
     */
    public final TableField<UserTagRecord, Date> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2010-01-01 00:00:00'", SQLDataType.LOCALDATETIME)), this, "", new LocalDateTimeConverter());

    /**
     * The column <code>uc.user_tag.modify_time</code>.
     */
    public final TableField<UserTagRecord, Date> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "", new LocalDateTimeConverter());

    /**
     * The column <code>uc.user_tag.env</code>.
     */
    public final TableField<UserTagRecord, String> ENV = createField(DSL.name("env"), SQLDataType.VARCHAR(8).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    private UserTag(Name alias, Table<UserTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTag(Name alias, Table<UserTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>uc.user_tag</code> table reference
     */
    public UserTag(String alias) {
        this(DSL.name(alias), USER_TAG);
    }

    /**
     * Create an aliased <code>uc.user_tag</code> table reference
     */
    public UserTag(Name alias) {
        this(alias, USER_TAG);
    }

    /**
     * Create a <code>uc.user_tag</code> table reference
     */
    public UserTag() {
        this(DSL.name("user_tag"), null);
    }

    public <O extends Record> UserTag(Table<O> child, ForeignKey<O, UserTagRecord> key) {
        super(child, key, USER_TAG);
    }

    @Override
    public Schema getSchema() {
        return Uc.UC;
    }

    @Override
    public Identity<UserTagRecord, Long> getIdentity() {
        return (Identity<UserTagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserTagRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    public List<UniqueKey<UserTagRecord>> getKeys() {
        return Arrays.<UniqueKey<UserTagRecord>>asList(Keys.CONSTRAINT_F);
    }

    @Override
    public UserTag as(String alias) {
        return new UserTag(DSL.name(alias), this);
    }

    @Override
    public UserTag as(Name alias) {
        return new UserTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTag rename(String name) {
        return new UserTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTag rename(Name name) {
        return new UserTag(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Date, Date, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
