/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc;


import com.katana.demo.entity.uc.tables.User;
import com.katana.demo.entity.uc.tables.UserAudit;
import com.katana.demo.entity.uc.tables.UserTag;
import com.katana.demo.entity.uc.tables.records.UserAuditRecord;
import com.katana.demo.entity.uc.tables.records.UserRecord;
import com.katana.demo.entity.uc.tables.records.UserTagRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * uc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> CONSTRAINT_2 = Internal.createUniqueKey(User.USER, DSL.name("CONSTRAINT_2"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserAuditRecord> CONSTRAINT_7 = Internal.createUniqueKey(UserAudit.USER_AUDIT, DSL.name("CONSTRAINT_7"), new TableField[] { UserAudit.USER_AUDIT.USERID }, true);
    public static final UniqueKey<UserTagRecord> CONSTRAINT_F = Internal.createUniqueKey(UserTag.USER_TAG, DSL.name("CONSTRAINT_F"), new TableField[] { UserTag.USER_TAG.ID }, true);
}
