/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc;


import com.katana.demo.entity.uc.tables.UserAudit;
import com.katana.demo.entity.uc.tables.UserInfo;
import com.katana.demo.entity.uc.tables.UserTag;


/**
 * Convenience access to all tables in uc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>uc.user_audit</code>.
     */
    public static final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * The table <code>uc.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * The table <code>uc.user_tag</code>.
     */
    public static final UserTag USER_TAG = UserTag.USER_TAG;
}
