/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc;


import com.katana.demo.entity.uc.tables.UserAudit;
import com.katana.demo.entity.uc.tables.UserInfo;
import com.katana.demo.entity.uc.tables.UserTag;


/**
 * Convenience access to all tables in uc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 用户审核表
     */
    public static final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * 用户信息表
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * 用户标签表
     */
    public static final UserTag USER_TAG = UserTag.USER_TAG;
}
