/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc;


import com.katana.demo.entity.DefaultCatalog;
import com.katana.demo.entity.uc.tables.User;
import com.katana.demo.entity.uc.tables.UserAudit;
import com.katana.demo.entity.uc.tables.UserTag;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>uc</code>
     */
    public static final Uc UC = new Uc();

    /**
     * The table <code>uc.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>uc.user_audit</code>.
     */
    public final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * The table <code>uc.user_tag</code>.
     */
    public final UserTag USER_TAG = UserTag.USER_TAG;

    /**
     * No further instances allowed
     */
    private Uc() {
        super("uc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER,
            UserAudit.USER_AUDIT,
            UserTag.USER_TAG);
    }
}
