/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc.tables.pojos;


import java.io.Serializable;
import java.util.Date;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String phone;
    private String email;
    private Date   createTime;
    private Date   updateTime;
    private String tenantCode;
    private String env;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.phone = value.phone;
        this.email = value.email;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.tenantCode = value.tenantCode;
        this.env = value.env;
    }

    public User(
        Long   id,
        String name,
        String phone,
        String email,
        Date   createTime,
        Date   updateTime,
        String tenantCode,
        String env
    ) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.tenantCode = tenantCode;
        this.env = env;
    }

    /**
     * Getter for <code>uc.User.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>uc.User.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>uc.User.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>uc.User.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>uc.User.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>uc.User.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>uc.User.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>uc.User.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>uc.User.create_time</code>.
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>uc.User.create_time</code>.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>uc.User.update_time</code>.
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>uc.User.update_time</code>.
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>uc.User.tenant_code</code>.
     */
    public String getTenantCode() {
        return this.tenantCode;
    }

    /**
     * Setter for <code>uc.User.tenant_code</code>.
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
    }

    /**
     * Getter for <code>uc.User.env</code>.
     */
    public String getEnv() {
        return this.env;
    }

    /**
     * Setter for <code>uc.User.env</code>.
     */
    public void setEnv(String env) {
        this.env = env;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(tenantCode);
        sb.append(", ").append(env);

        sb.append(")");
        return sb.toString();
    }
}
