/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAudit implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    userid;
    private String  name;
    private Integer auditState;
    private Long    auditorId;
    private String  reasonCode;
    private String  refuseReason;
    private String  env;

    public UserAudit() {}

    public UserAudit(UserAudit value) {
        this.userid = value.userid;
        this.name = value.name;
        this.auditState = value.auditState;
        this.auditorId = value.auditorId;
        this.reasonCode = value.reasonCode;
        this.refuseReason = value.refuseReason;
        this.env = value.env;
    }

    public UserAudit(
        Long    userid,
        String  name,
        Integer auditState,
        Long    auditorId,
        String  reasonCode,
        String  refuseReason,
        String  env
    ) {
        this.userid = userid;
        this.name = name;
        this.auditState = auditState;
        this.auditorId = auditorId;
        this.reasonCode = reasonCode;
        this.refuseReason = refuseReason;
        this.env = env;
    }

    /**
     * Getter for <code>uc.user_audit.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>uc.user_audit.userid</code>.
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>uc.user_audit.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>uc.user_audit.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>uc.user_audit.audit_state</code>.
     */
    public Integer getAuditState() {
        return this.auditState;
    }

    /**
     * Setter for <code>uc.user_audit.audit_state</code>.
     */
    public void setAuditState(Integer auditState) {
        this.auditState = auditState;
    }

    /**
     * Getter for <code>uc.user_audit.auditor_id</code>.
     */
    public Long getAuditorId() {
        return this.auditorId;
    }

    /**
     * Setter for <code>uc.user_audit.auditor_id</code>.
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * Getter for <code>uc.user_audit.reason_code</code>.
     */
    public String getReasonCode() {
        return this.reasonCode;
    }

    /**
     * Setter for <code>uc.user_audit.reason_code</code>.
     */
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }

    /**
     * Getter for <code>uc.user_audit.refuse_reason</code>.
     */
    public String getRefuseReason() {
        return this.refuseReason;
    }

    /**
     * Setter for <code>uc.user_audit.refuse_reason</code>.
     */
    public void setRefuseReason(String refuseReason) {
        this.refuseReason = refuseReason;
    }

    /**
     * Getter for <code>uc.user_audit.env</code>.
     */
    public String getEnv() {
        return this.env;
    }

    /**
     * Setter for <code>uc.user_audit.env</code>.
     */
    public void setEnv(String env) {
        this.env = env;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAudit (");

        sb.append(userid);
        sb.append(", ").append(name);
        sb.append(", ").append(auditState);
        sb.append(", ").append(auditorId);
        sb.append(", ").append(reasonCode);
        sb.append(", ").append(refuseReason);
        sb.append(", ").append(env);

        sb.append(")");
        return sb.toString();
    }
}
