/*
 * This file is generated by jOOQ.
 */
package com.katana.demo.entity.uc.tables.pojos;


import java.io.Serializable;
import java.util.Date;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   userid;
    private String tag;
    private Date   createTime;
    private Date   modifyTime;
    private String env;

    public UserTag() {}

    public UserTag(UserTag value) {
        this.id = value.id;
        this.userid = value.userid;
        this.tag = value.tag;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this.env = value.env;
    }

    public UserTag(
        Long   id,
        Long   userid,
        String tag,
        Date   createTime,
        Date   modifyTime,
        String env
    ) {
        this.id = id;
        this.userid = userid;
        this.tag = tag;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.env = env;
    }

    /**
     * Getter for <code>uc.user_tag.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>uc.user_tag.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>uc.user_tag.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>uc.user_tag.userid</code>.
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>uc.user_tag.tag</code>.
     */
    public String getTag() {
        return this.tag;
    }

    /**
     * Setter for <code>uc.user_tag.tag</code>.
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Getter for <code>uc.user_tag.create_time</code>.
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>uc.user_tag.create_time</code>.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>uc.user_tag.modify_time</code>.
     */
    public Date getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>uc.user_tag.modify_time</code>.
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>uc.user_tag.env</code>.
     */
    public String getEnv() {
        return this.env;
    }

    /**
     * Setter for <code>uc.user_tag.env</code>.
     */
    public void setEnv(String env) {
        this.env = env;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserTag (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(tag);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(env);

        sb.append(")");
        return sb.toString();
    }
}
